### ISSUE TITLE
Auto-publish to PyPi

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/doi2ietf-py#5]
Update GHA workflow to achieve that, only publish when tests pass.

**Comment by strogonoff** [comment]
Publication fails with authentication error, @ronaldtse are authentication secrets correct?

https://github.com/ietf-ribose/doi2ietf-py/runs/3311528277?check_suite_focus=true#step:7:23

**Comment by ronaldtse** [comment]
@strogonoff yes, the secret is correct.

**Comment by ronaldtse** [comment]
You may want to try pushing a new version since the current version is already published.

**Comment by strogonoff** [comment]
@ronaldtse I don’t see a successful “release” action in GHA history for this repo. Are you sure? Did you publish by hand?

**Comment by strogonoff** [comment]
(The workflow is currently set up to publish to test PyPI registry)

**Comment by ronaldtse** [comment]
By hand.

**Comment by ronaldtse** [comment]
The problem is this:

https://github.com/pypa/gh-action-pypi-publish
```
- name: Publish package
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
```

The user should be `__token__`.
